### PR TITLE
Update flat rate whitelist to support multiple admins

### PR DESCRIPTION
**Pull request by MightOfOaks**

### CODE REVIEW

**Review by jason-c-child — COMMENTED** [review]
Are there other instances where we support multiple admins in our contracts?

**Comment by MightOfOaks** [comment]
> Are there other instances where we support multiple admins in our contracts?

https://github.com/public-awesome/launchpad/tree/main/contracts/whitelists/whitelist is an example.

We mainly need it to set the dYdX airdrop contract as an admin after its instantiation while still maintaining manual access just in case.

**Comment by jason-c-child** [comment]
> > Are there other instances where we support multiple admins in our contracts?
> 
> 
> 
> https://github.com/public-awesome/launchpad/tree/main/contracts/whitelists/whitelist is an example.
> 
> 
> 
> We mainly need it to set the dYdX airdrop contract as an admin after its instantiation while still maintaining manual access just in case.

Sweet, sgtm

**Review by jason-c-child — APPROVED** [review]
looks good 😊

**Pull request merged**
